### ISSUE TITLE
Split code

### ISSUE THREAD

**Issue by KaiZhuPhD** [claraqin/beta_regression#4]
@claraqin Split the code by sections into difference code files, e.g., simulate data, JAGS inference, validate the model. Easier to organize as the code is getting longer.

**Comment by claraqin** [comment]
I just split the code into three files: glmmTMB_demo.R, simulate_jags_data.R, and run_jags.R. Does this address the issue for now?

**Comment by KaiZhuPhD** [comment]
Yes, thanks.
